// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mobile/models/blocked_history.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BlockedHistoryAdapter());
  }
}
